apiVersion: v1
kind: Service
metadata:
  labels:
    servicename: nginx
  name: nginx
  namespace: www
spec:
  type: NodePort
  ports:
  - name: "http"
    port: 80
    targetPort: 80
    nodePort: 31080
  - name: "https"
    port: 443
    targetPort: 443
    nodePort: 31443
  selector:
    servicename: nginx
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    servicename: nginx
  name: nginx
  namespace: www
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      servicename: nginx
  template:
    metadata:
      labels:
        servicename: nginx
    spec:
      containers:
      - args:
        - nginx-debug
        - -g
        - daemon off;
        image: nginx
        name: nginx
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /
            port: 80
          initialDelaySeconds: 3
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 5
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          requests:
            cpu: "250m"
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/default.conf
          name: config-volume
          subPath: default.conf
#        - mountPath: /etc/nginx-crt-key
#          name: nginx-crt-key
#          readOnly: true
        - mountPath: /var/www/html
          name: www-claim
      restartPolicy: Always
      volumes:
      - name: config-volume
        configMap:
          name: default.conf.cm
#      - name: nginx-crt-key
#        secret:
#          secretName: nginx-crt-key
      - name: www-claim
        hostPath:
          path: /mnt/www
          type: Directory
status: {}
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-nginx
  namespace: www
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
