apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: www-claim
  namespace: www
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
